version: '3.8'

services:
  ghost-mysql:
    image: mysql:5.7  # Recommended MySQL version for compatibility
    container_name: ghost-mysql
    volumes:
      - ${PROJECT_ROOT_FOLDER}/${PROJECT_NAME}/blog/db/ghost_data_mysql:/var/lib/mysql:z 
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghost
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    restart: always 
    networks:
      - ghost-network

  ghost:
    container_name: ghost
    image: ghost:5.79.4  # Use the latest Ghost image
    ports:
      - "2368:2368"
    volumes:
      - ${PROJECT_ROOT_FOLDER}/${PROJECT_NAME}/blog/ghost/content:/var/lib/ghost/content:z # 持久化内容
      - ${PROJECT_ROOT_FOLDER}/${PROJECT_NAME}/blog/ghost/config.production.json:/var/lib/ghost/config.production.json:z # Overwrite default settings
    environment:
      NODE_ENV: production # set production or development
      url: https://${DOMAIN_NAME}  # Local test: http://localhost:2386
      TZ: Asia/Shanghai  # 设置环境变量
    expose:
      - "3306"
    restart: always # 设置 Ghost 服务的重启策略为 always
    depends_on:
      - ghost-mysql
    networks:
      - ghost-network

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PROJECT_ROOT_FOLDER}/${PROJECT_NAME}/blog/nginx/conf.d/:/etc/nginx/conf.d/
      - ${PROJECT_ROOT_FOLDER}/${PROJECT_NAME}/ghost-docker-compose-deploy/certs/${DOMAIN_NAME}.key:/etc/nginx/${DOMAIN_NAME}.key:ro
      - ${PROJECT_ROOT_FOLDER}/${PROJECT_NAME}/certs/fullchain.cer:/etc/nginx/fullchain.cer:ro
    restart: always 
    depends_on:
      - ghost
    networks:
      - ghost-network

networks:
  ghost-network:
    name: ghost-network
    driver: bridge
    